volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - REDIS_HOST=${REDIS_HOST:-romm-redis}
      - DB_HOST=${DB_HOST:-romm-db}
      - DB_NAME=${DB_NAME:-romm}
      - DB_USER=${DB_USER:-romm}
      - DB_PASSWD=${DB_PASSWD:-rommpassword}
      - ROMM_BASE_PATH=/romm
    ports:
      - "80:8080" # Maps port 80 of your machine to RomM (access via http://localhost)
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - ./romm_data/library:/romm/library
      - ./romm_data/assets:/romm/assets
      - ./romm_data/config:/romm/config
    depends_on:
      romm-db:
        condition: service_healthy
      romm-redis:
        condition: service_healthy

  romm-db:
    image: mariadb:10.11
    container_name: romm-db
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWD:-rootpassword}
      - MARIADB_DATABASE=${DB_NAME:-romm}
      - MARIADB_USER=${DB_USER:-romm}
      - MARIADB_PASSWORD=${DB_PASSWD:-rommpassword}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  romm-redis:
    image: redis:alpine
    container_name: romm-redis
    restart: unless-stopped
    volumes:
      - romm_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
